# Generated by Django 4.0.4 on 2022-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='diffulty_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_target',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
