# Generated by Django 4.0.4 on 2022-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_diffulty_level_workout_workout_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='diffulty_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
