# Generated by Django 4.0.4 on 2022-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_diffulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='resistance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
