# Generated by Django 4.0.4 on 2022-11-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_userexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='weight',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='resistance',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
