# Generated by Django 4.0.4 on 2022-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_equipment_exercise_resistance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_exercises', through='exercises.WorkoutExercise', to='exercises.exercise'),
        ),
    ]
