# Generated by Django 4.0.4 on 2022-11-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_remove_userexercise_weight_userexercise_resistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exercises_info', to='exercises.exercise'),
        ),
    ]
