# Generated by Django 4.0.4 on 2022-11-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_userexercise_exercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='diffulty_level',
            new_name='difficulty_level',
        ),
    ]
