# Generated by Django 4.0.4 on 2022-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_alter_workout_workout_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateTimeField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
