# Generated by Django 4.0.4 on 2022-11-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_rename_diffulty_level_exercise_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='quantity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
