# Generated by Django 4.0.4 on 2022-06-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_dailyworkouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkouts',
            name='workout_date',
            field=models.DateField(),
        ),
    ]
