# Generated by Django 4.0.4 on 2022-11-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='quantity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
