# Generated by Django 4.0.4 on 2022-06-24 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_alter_dailyworkouts_workout_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyworkouts',
            old_name='count',
            new_name='total_workouts',
        ),
    ]
