# Generated by Django 4.0.4 on 2022-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_rename_count_dailyworkouts_total_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkouts',
            name='status',
            field=models.CharField(default='started', max_length=8),
            preserve_default=False,
        ),
    ]
