# Generated by Django 4.0.4 on 2022-12-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_user_subscription_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyWorkouts',
            new_name='DailyWorkout',
        ),
        migrations.RenameModel(
            old_name='FavoriteWorkouts',
            new_name='FavoriteWorkout',
        ),
    ]
