# Generated by Django 4.0.4 on 2022-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_dailyworkouts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='total_rounds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
