# Generated by Django 4.0.4 on 2022-12-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_rename_dailyworkouts_dailyworkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
