# Generated by Django 4.0.4 on 2022-12-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_user_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
