# Generated by Django 4.0.4 on 2022-12-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_user_token_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
